// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PhoneNumberController from "./phone_number_controller"
application.register("phone-number", PhoneNumberController)

import PreviewsController from "./previews_controller"
application.register("previews", PreviewsController)

import PasswordVisibility from '@stimulus-components/password-visibility'
application.register('password-visibility', PasswordVisibility)

import Dropdown from '@stimulus-components/dropdown'
application.register('dropdown', Dropdown)

import Notification from '@stimulus-components/notification'
application.register('notification', Notification)